apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-server.fullname" . }}-secrets
  labels:
    {{- include "app-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  googleClientId: {{ .Values.secrets.googleClientId | quote }}
  googleClientSecret: {{ .Values.secrets.googleClientSecret | quote }}
  googleRedirectUri: {{ .Values.secrets.googleRedirectUri | quote }}
  jwtSecret: {{ .Values.secrets.jwtSecret | quote }}
  allowedEmail: {{ .Values.secrets.allowedEmail | quote }}
  frontendUrl: {{ .Values.secrets.frontendUrl | quote }}
  backendUrl: {{ .Values.secrets.backendUrl | quote }}
  userServiceUrl: {{ .Values.secrets.userServiceUrl | quote }}
  agentServiceUrl: {{ .Values.secrets.agentServiceUrl | quote }}
  stravaServiceUrl: {{ .Values.secrets.stravaServiceUrl | quote }}
  tablesServiceUrl: {{ .Values.secrets.tablesServiceUrl | quote }}
