apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-service.fullname" . }}-secrets
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  databaseUrl: {{ .Values.secrets.databaseUrl | quote }}
