apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources/bitnami.yaml
  - sources/grafana.yaml
  - sources/prometheus-community.yaml
  - cloudflared/namespace.yaml
  - cloudflared/configmap.yaml
  - cloudflared/deployment.yaml
  - monitoring/namespace.yaml
  - monitoring/kube-prometheus-stack.yaml
  - monitoring/loki.yaml
  - monitoring/promtail.yaml
