{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "app-server.fullname" . }}
  labels:
    {{- include "app-server.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "app-server.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
{{- end }}
