packages:
  - apps/*
  - services/@*/*
  - packages/@website/*
  - packages/@crow/*
  - packages/@agent/*
  - packages/@tools/*
  - packages/@cli/*
  - packages/@signal/*

catalog:
  '@biomejs/biome': 2.2.6
  '@typescript/native-preview': 7.0.0-dev.20251017.1

forceLegacyDeploy: true

onlyBuiltDependencies:
  - '@prisma/engines'
  - better-sqlite3
  - core-js
  - esbuild
  - prisma
