---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: 86ffa052-fefa-4ec1-ba6a-28cfc1c5efa0
    credentials-file: /etc/cloudflared/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
      - hostname: www.crowprose.com
        service: http://www-web.default.svc.cluster.local:80
      - hostname: crowprose.com
        service: http://www-web.default.svc.cluster.local:80
      - hostname: app.crowprose.com
        service: http://app-web.default.svc.cluster.local:80
      - hostname: api.crowprose.com
        service: http://api-service.default.svc.cluster.local:3000
      - hostname: o11y.crowprose.com
        service: http://monitoring-grafana.monitoring.svc.cluster.local:80
      # Catch-all rule (required by cloudflared)
      - service: http_status:404
