---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: agent-service
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: ./services/@agent/service/helm
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      reconcileStrategy: Revision
      valuesFiles:
        - ./services/@agent/service/helm/values.yaml
        - ./services/@agent/service/helm/values-selfhosted.yaml
  values:
    image:
      tag: selfhosted-sha-47b601da7a5658954e116ddb8d2bbd3af7ea2be9
  valuesFrom:
    - kind: Secret
      name: agent-service-secrets-values
      valuesKey: databaseUrl
      targetPath: secrets.databaseUrl
    - kind: Secret
      name: agent-service-secrets-values
      valuesKey: anthropicApiKey
      targetPath: secrets.anthropicApiKey
    - kind: Secret
      name: agent-service-secrets-values
      valuesKey: braveApiKey
      targetPath: secrets.braveApiKey
