---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: app-web
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: ./apps/dashboard/helm
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      reconcileStrategy: Revision
      valuesFiles:
        - ./apps/dashboard/helm/values.yaml
        - ./apps/dashboard/helm/values-selfhosted.yaml
  values:
    image:
      tag: selfhosted-sha-4163d7f2034634532d01863508a3bb343fa7fa5a
