---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tables-service
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: ./services/@tables/service/helm
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      reconcileStrategy: Revision
      valuesFiles:
        - values.yaml
        - values-selfhosted.yaml
  values:
    image:
      tag: latest
  valuesFrom:
    - kind: Secret
      name: tables-service-secrets-values
      valuesKey: databaseUrl
      targetPath: secrets.databaseUrl
    - kind: Secret
      name: tables-service-secrets-values
      valuesKey: anthropicApiKey
      targetPath: secrets.anthropicApiKey
