---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: user-service
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: ./services/@users/service/helm
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      reconcileStrategy: Revision
      valuesFiles:
        - ./services/@users/service/helm/values.yaml
        - ./services/@users/service/helm/values-selfhosted.yaml
  values:
    image:
      tag: selfhosted-sha-8c704bb39431d4fe2bc902c99fb49bedd2be6a91
  valuesFrom:
    - kind: Secret
      name: user-service-secrets-values
      valuesKey: databaseUrl
      targetPath: secrets.databaseUrl
